name: Aqua CI
on:
  push:
    branches: [ aqua_dev_central ]
  pull_request:
    branches: [ aqua_dev_central ]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: 17.0.2+8
      - name: Run ktlint with reviewdog
        uses: ScaCap/action-ktlint@1.3
      - name: Build with Gradle
        run: ./gradlew build
