name: Test Runner

on: 
  pull_request:
    branches: [ aqua_dev_central ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: 17.0.2+8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Unit Tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build
